FROM docker.io/kubevirt/container-disk-v1alpha

LABEL maintainer="The KubeVirt Project <kubevirt-dev@googlegroups.com>"

ARG SRC_FILE="NO_ARG_GIVEN_ARGHHH!!!!"
ARG DEST_FILE="NO_ARG_GIVEN_ARGHHH!!!!"

ADD ../images/$SRC_FILE /disk/$DEST_FILE
