sudo: required
dist: xenial

install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y software-properties-common uidmap
  - sudo add-apt-repository -y ppa:projectatomic/ppa
  - sudo apt-get update -qq
  - sudo apt-get -qq -y install buildah podman

script:
  - buildah --version
  - podman --version
  - ./fetch.sh
  - ./build.sh
  - ./push.sh
 
